export const products = [
  {
    slug: "utilities-coops",
    name: "Distribution Utilities & Rural Cooperatives",
    shortName: "Utilities & Co-ops",
    eyebrow: "Product 01",
    summary: "Distribution grid agents for zero-shot power-flow solving and cyber-resilient control on SmartDSS systems the model has never seen, with 0 system-specific fine-tuning.",
    headline: "Grid agents for unseen distribution systems.",
    lead: "WattsMIND Grid Agent processes OpenDSS circuit files, learns the physical structure of SmartDSS-randomized distribution systems, and supports two core workflows: fast learned power-flow solves and agent control for cyber-attack mitigation, with 0 system-specific fine-tuning at test time.",
    applications: [
      "Fast three-phase power-flow voltage solves",
      "Zero-shot phasor solutions on unseen circuit topologies",
      "Agent control for cyber-attack mitigation",
      "Surrogate evaluation for distribution studies and operating scenarios",
    ],
    value: [
      "Turns raw circuit descriptions into voltage phasor solutions.",
      "Controls phase imbalance under device-level attack scenarios.",
      "Avoids fitting a separate model for every feeder topology or attack case.",
    ],
    metric: "0",
    metricLabel: "system-specific fine-tuning on held-out DSS systems",
  },
  {
    slug: "embedded-engines",
    name: "Embedded Grid Engines",
    shortName: "Embedded Engines",
    eyebrow: "Product 02",
    summary: "A certifiable AI engine for grid software and services vendors that need faster analytics inside existing platforms.",
    headline: "Grid intelligence that vendors can embed.",
    lead: "WattsMIND Grid Agent can be delivered as an API, on-prem engine, or model component inside planning, monitoring, and control products that already serve utilities and operators.",
    applications: [
      "N-k contingency screening modules",
      "Planning-study acceleration",
      "State estimation and topology transfer services",
      "Vendor platform benchmarking and integration",
    ],
    value: [
      "Adds differentiated AI capability without rebuilding the vendor application.",
      "Supports deployment models compatible with enterprise grid customers.",
      "Turns one transferable model into many customer deployments.",
    ],
    metric: "API",
    metricLabel: "delivery model for software integration",
  },
  {
    slug: "transmission-isos",
    name: "Transmission Operators & ISOs/RTOs",
    shortName: "Transmission & ISOs/RTOs",
    eyebrow: "Product 03",
    summary: "Fast contingency, congestion, and control intelligence for high-stakes transmission operations.",
    headline: "Screen more network risk before it becomes operational risk.",
    lead: "For transmission operators and market operators, WattsMIND Grid Agent focuses on rapid screening, feasible recommendations, and explainable confidence under changing network conditions.",
    applications: [
      "Fast N-k contingency screening",
      "Congestion and constraint analytics",
      "Real-time operating-limit awareness",
      "Operator-facing decision support",
    ],
    value: [
      "Compresses repeated studies into fast inference and verification loops.",
      "Keeps feasibility and certificates close to every recommendation.",
      "Provides a path from planning insight to control-room action.",
    ],
    metric: "N-k",
    metricLabel: "contingency screening focus",
  },
  {
    slug: "energy-markets",
    name: "Energy Market Participants",
    shortName: "Energy Markets",
    eyebrow: "Product 04",
    summary: "Physics-aware congestion and dispatch intelligence for trading, asset optimization, and market analytics teams.",
    headline: "Market signals grounded in the physics of the grid.",
    lead: "WattsMIND Grid Agent helps market participants reason about congestion, dispatch feasibility, and network constraints without treating the power system as a black box.",
    applications: [
      "Congestion intelligence",
      "Dispatch and constraint forecasting",
      "Asset optimization signals",
      "Market-aware operational analytics",
    ],
    value: [
      "Connects market views to grid constraints and feasible operating states.",
      "Supports faster scenario evaluation across changing topology assumptions.",
      "Turns physics-informed inference into actionable market intelligence.",
    ],
    metric: "RT",
    metricLabel: "real-time analytics orientation",
  },
  {
    slug: "flexible-loads",
    name: "Large Flexible Loads",
    shortName: "Flexible Loads",
    eyebrow: "Product 05",
    summary: "Grid-aware coordination for data centers and other controllable loads that need operational flexibility.",
    headline: "Make flexible demand behave like a grid asset.",
    lead: "For data centers and large controllable loads, WattsMIND Grid Agent supports interconnection insight, risk-aware operation, and real-time flexibility decisions aligned with grid conditions.",
    applications: [
      "Data-center flexibility scheduling",
      "Grid-aware load coordination",
      "Interconnection and operating-risk insight",
      "Behind-the-meter dispatch support",
    ],
    value: [
      "Helps large loads respond to grid conditions without compromising operations.",
      "Links flexibility decisions to congestion, constraints, and feasible controls.",
      "Creates a bridge between power procurement and grid operations.",
    ],
    metric: "MW",
    metricLabel: "controllable load coordination",
  },
] as const;

export type Product = (typeof products)[number];
